### ISSUE TITLE
compilation fails with flint.h not found

### ISSUE THREAD

**Issue by rwst** [wbhart/flint2#217]
When compiling the symengine.py package I get the error 

```
/usr/local/include/flint/flintxx/flint_classes.h:30:19: fatal error: flint.h: No such file or directory
```

which is because `"flint.h"` is included not `<flint/flint.h>`.
A similar issue is https://github.com/fredrik-johansson/arb/issues/24

**Comment by wbhart** [comment]
I don't believe flint_classes.h is a flint file. It must be something to do
with symengine.py. Perhaps you could alert them to this issue, as I don't
believe there is anything we can do at this end to fix it.

Bill.

**Comment by isuruf** [comment]
It is a flint file https://github.com/wbhart/flint2/blob/trunk/flintxx/flint_classes.h.
This is a file that is installed. `/usr/local/flint/flintxx/flint_classes.h`

When using C++ wrappers of flint, for example `fmpq_polyxx.h` then this file is included which in turn includes `flint.h`.

`fmpq_polyxx.h` and `flint.h` are in the same folder which makes `#include "flint.h"` work fine.
`flint_classes.h` and `flint.h` are not in the same folder which means  `#include "flint.h"` won't work.

**Comment by isuruf** [comment]
Solution would be to change this line https://github.com/wbhart/flint2/blob/trunk/flintxx/flint_classes.h#L30 to `#include "../flint.h"` or `#include "flint/flint.h"`

**Comment by wbhart** [comment]
I am sorry. I was looking for flint_classes.h at the top level of flint. My
mistake.

Unfortunately I don't quite know the solution for this problem. If we
change it as suggested the test code will break. I will give it some
thought.

**Comment by wbhart** [comment]
Actually, I think your first suggestion will work.

**Comment by wbhart** [comment]
I have committed the first fix suggested above. It appears to pass the test
code.

**Comment by certik** [comment]
@wbhart looks like you don't use your C++ stuff much if you forgot about the files that are involved. ;) It seems to be working pretty well though I think.

**Comment by wbhart** [comment]
Yeah I don't use C++ at all. I had no recollection of that file whatsoever.
All the .h files I know of are at the top level.

Anyway, thanks very much for the positive build report!

**Comment by kiwifb** [comment]
I know I am a bit late to the party, I just saw this through a bug on `sagemath` but I would have favored `flint/flint.h` who does ship with `../XXX.h` headers? Actually I think it would a better design if `flintxx` was a folder alongside the `flint` one rather than inside.
