### ISSUE TITLE
-std=c99 must not be used in c++ calls

### ISSUE THREAD

**Issue by dimpase** [wbhart/flint2#434]
with clang-4.0.0 on FreeBSD (this is the default C++ on FreeBSD 11.1) I get
```
[flint-2.5.2.p1] c++ -fPIC -std=c99 -pedantic -Wall -O2 -funroll-loops -g -mpopcnt  -Wno-unknown-pragmas -I/usr/home/dima/Sage/sage/local/var/tmp/sage/build/flint-2.5.2.p1/src -I/usr/home/dima/Sage/sage/local/include -I/usr/home/dima/Sage/sage/local/include -I/usr/home/dima/Sage/sage/local/include -c interfaces/NTL-interface.cpp -o build/interfaces/NTL-interface.lo
[flint-2.5.2.p1] error: invalid argument '-std=c99' not allowed with 'C++/ObjC++'
```

**Comment by wbhart** [comment]
I vaguely recall this is fixed in trunk.

**Comment by dimpase** [comment]
I am using configure from the trunk (so, no, it's not fixed). It seems that
one has to specifically set
CXXFLAGS with the correct `-std=` for this case. I'll submit a pull request
once I've
tested this.
